# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_auto_20170127_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
    ]
